version: 2.0

references:
  container_config: &container_config
    docker:
      - image: circleci/node:latest
    working_directory: ~/ghpages-sandbox

  workspace_root: &workspace_root
      /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build-and-deploy:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install yarn
          command: sudo npm install -g yarn
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build then Deploy
          command:
            yarn build
            && mkdir -p /tmp/workspace
            && cp -r dist/* /tmp/workspace
            && ./scripts/deploy-master.sh /tmp/workspace

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-deploy